# Generated by Django 4.1.4 on 2024-02-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='pages',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
