# Generated by Django 4.1.4 on 2024-02-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_alter_booksmodel_pages_alter_booksmodel_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BooksModel',
            new_name='Books',
        ),
    ]
